#!/usr/bin/env python3

import os
import getpass
import csv
import pwd
import grp
import argparse
import configparser

# check for admin privileges
if getpass.getuser() != 'root' and os.geteuid != 0:
    print('error: this command must be run as root user')
    exit(1)

config = configparser.ConfigParser()
if config.read('/etc/ad/settings.cfg') == []:
    print('error: cannot read configuration file')
    exit(1)

SAMBA_PATH = config['GLOBAL']['samba_path']
SERVER_NAME = config['GLOBAL']['server_name']
USERS_FS_PATH = config['GLOBAL']['home_dirs_path']
DOMAIN_NAME = config['GLOBAL']['nt_domain_name']
POOL_PATH = config['GLOBAL']['pool_path']
POOL_OWNER = config['GLOBAL']['pool_owner']

parser = argparse.ArgumentParser()
parser.add_argument("-f", "--filename", help="create links for all users in file")
args = parser.parse_args()

# Add users from csv
def add_from_csv(filepath):
    with open(filepath) as csv_file:
        line_count = 0
        csv_reader = csv.reader(csv_file, delimiter=';')

        for row in csv_reader:
            if len(row) != 8:
                print(f'error: invalid csv format on line {line_count}')
                exit(1)

            username = row[0]
            groups = [row[3], row[4]] if row[4] != '' else [row[3]]
            if len(groups) != 2:
                print(f'error: user {username} has no parent group, skipping link creation...')
                line_count += 1
                continue

            # create directories
            if not os.path.exists(f'{POOL_PATH}/{groups[1]}'):
                os.mkdir(f'{POOL_PATH}/{groups[1]}')
                uid = pwd.getpwnam(f"administrator@{DOMAIN_NAME}").pw_uid
                gid = grp.getgrnam(f'{DOMAIN_NAME}\\{POOL_OWNER}').gr_gid
                os.chown(f'{POOL_PATH}/{groups[1]}', uid, gid)
            
            # create symlink
            src = f'{USERS_FS_PATH}/{username}'
            dst = f'{POOL_PATH}/{groups[1]}/{username}'
            if not os.path.exists(dst):
                print(f'linking {src} to {dst}')
                os.symlink(f'{USERS_FS_PATH}/{username}', f'{POOL_PATH}/{groups[1]}/{username}', target_is_directory=True)
            
            line_count +=1

if args.filename:
    add_from_csv(args.filename)
    exit(0)
